### ISSUE TITLE
Sort order not respected

### ISSUE THREAD

**Issue by frontedbe** [mmikkel/ChildMe-Craft#2]
Hi!
How does the sort order of child elements get determined? I added numbers to indicate which item needs to come first and last but this somehow doesn't take into effect..
[screenshot](https://cl.ly/87a8f4e490a7)
Any ideas? Thanks!

**Comment by frontedbe** [comment]
I've also changed the handles of those entry types but no effect unfortunately

**Comment by mmikkel** [comment]
Hi @mdominguez, thanks for reporting.

I'll look into a fix for this ASAP.

**Comment by mmikkel** [comment]
Hi @mdominguez, this should be resolved w/ [Child Me! v. 1.0.5](https://github.com/mmikkel/ChildMe-Craft/releases/tag/1.0.5). 

Sorry for being extremely slow on the ball here!
