### ISSUE TITLE
Plus sign appears on entry selectors

### ISSUE THREAD

**Issue by larsboldt** [mmikkel/ChildMe-Craft#20]
If you have a field for selecting entries and you collapse and then expand a structured section you get the plus sign (nothing happens if you click it). Default state (expanded) does not show plus sign.

**Comment by mmikkel** [comment]
Thanks @larsboldt – nice catch. Will get that fixed ASAP.

**Comment by mmikkel** [comment]
Took a while, but this should be resolved in [Child Me! v. 1.3.3](https://github.com/mmikkel/ChildMe-Craft/releases/tag/1.3.3).
