### ISSUE TITLE
Empty new child column

### ISSUE THREAD

**Issue by fdelaneau** [mmikkel/ChildMe-Craft#21]
Added ChildMe 2.0.0 plugin to an existing site using the latest Craft 5.0.5, I added the New Child column to my structure view and I get an empty column, no plus icon at all and the column title is displayed.

<img width="965" alt="Capture d’écran 2024-04-26 à 12 37 03" src="https://github.com/mmikkel/ChildMe-Craft/assets/129808/52b0c977-e967-43c3-b9da-be305d522efd">

Note that I have an other Craft 5.0.5 site, migrated from version 4 where the plugin was already installed and it does work flawlessly. The plus icon is added and functionnal, the column title is hidden.

**Comment by mmikkel** [comment]
Hi @fdelaneau – hm, that's strange. 

This is expected behavior if the "New child" attribute is added to a section that is a) not a structure, or b) has its "Max Limit" setting set to `1`.

What's your structure section's "Max Levels" setting set to?

**Comment by mmikkel** [comment]
Ran into this myself and believe I got it sorted in [Child Me! v. 2.1.0](https://github.com/mmikkel/ChildMe-Craft/releases/tag/2.1.0) 🎉
