### ISSUE TITLE
Request: Limit the depth of children

### ISSUE THREAD

**Issue by gbaumbach** [mmikkel/ChildMe-Craft#3]
It would be great if you could set a limit as to how deep children can go. Knowing my clients--they almost certainly will unknowingly add children upon children within children until the URI stretches the length of a football field. Could be a global variable in the plugin itself--or even better being able to set based on the section. This is a great addition to Craft though regardless, thank you!

**Comment by mmikkel** [comment]
Hi @gbaumbach,

There's a native "Max Levels" setting for both Structures and Category Groups, which Child Me! will honor.

**Comment by gbaumbach** [comment]
Ha--I completely missed that option. Now we're cooking. Thx!
