### ISSUE TITLE
Broken for multi-site installs

### ISSUE THREAD

**Issue by rungta** [mmikkel/ChildMe-Craft#7]
https://github.com/mmikkel/ChildMe-Craft/blob/2c14bbe6bb380bc38ed62ac2c5bd4688c21b3b31/src/resources/childme.js#L197

Child Me appears to be appending the site handle to the new entry URL, resulting in something like: `/admin/entries/<sectionHandle>/new/<siteHandle>?typeId=10&parentId=83&site=<siteHandle>` which leads to a 404. Removing the last `<siteHandle>` segment from the URL (`/admin/entries/<sectionHandle>/new?typeId=10&parentId=83&site=<siteHandle>`) fixes this. This bug only appears on non-primary sites. The plugin’s links work just fine on the primary site.

Craft version: 3.4.14
Plugin version: 1.1.0

**Comment by mmikkel** [comment]
Hi @rungta, this should be resolved in [Child Me! v. 1.1.1](https://github.com/mmikkel/ChildMe-Craft/releases/tag/1.1.1).

**Comment by rungta** [comment]
Thanks @mmikkel!

**Comment by mmikkel** [comment]
Thanks for reporting, @rungta :)
