### ISSUE TITLE
Adding Children in Draft

### ISSUE THREAD

**Issue by laurabennett** [mmikkel/ChildMe-Craft#9]
The default behavior in Craft 3.6.12 seems to be to create a draft first and then click to save or publish. 
Not sure if this is really a @craftcms bug or childMe.
If I try to add a child to a draft entry it saves as a sibling. I then tried dragging it to be a child which appears to work, however once I publish the child again becomes a sibling.

**Comment by mmikkel** [comment]
Sorry for missing this issue, @laurabennett. Not able to reproduce, so possibly it's been fixed (either in Child Me! or in Craft) since. Let me know if it's still a problem!

**Comment by laurabennett** [comment]
I also can no longer reproduce the issue. Thanks!
